tsvetanovv

medium

# Not check for the valid round in Sequencer

## Summary

When checking sequencer uptime, it is mandatory to also check for a valid round.

## Vulnerability Detail

In `ChainLinkOracle.sol` we have `_checkSequencer()`:
```solidity
function _checkSequencer() internal view {
        (, int256 answer, uint256 startedAt, , ) = sequencerUptimeFeed
            .latestRoundData();

        require(answer == 0, "ChainLinkOracle: sequencer down");

        // Make sure the grace period has passed after the
        // sequencer is back up.
        require(
            block.timestamp - startedAt > GRACE_PERIOD_TIME, // solhint-disable-line not-rely-on-time, max-line-length
            "ChainLinkOracle: grace period not over"
        );
    }
```

This function checks the status of the sequencer and ensures that a grace period has passed since the sequencer status changed.
But this function is missing one very important check. According to the Chainlink documentation:

>`startedAt`: This timestamp indicates when the sequencer changed status. This timestamp returns `0` if a round is invalid.

https://docs.chain.link/data-feeds/l2-sequencer-feeds#example-code

## Impact

Failure to check for a valid round will result in an incorrect status of Sequencer. 

## Code Snippet

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-manager-templates/contracts/oracles/ChainLinkOracle.sol#L148-L161
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-manager-templates/contracts/oracles/ChainLinkOraclePivot.sol#L277-L290

## Tool used

Manual Review

## Recommendation

Check round validity:

```solidity
require(startedAt != 0, "_checkSequencer(): invalid round")
```